version: '3.1'

services:

  mysql_database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    depends_on: 
     - mysql_database
    environment:
      WORDPRESS_DB_HOST: mysql_database
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - wordpress:/var/www/html

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
     PMA_HOST: mysql_database
     MYSQL_ROOT_PASSWORD: 1234


volumes:
  wordpress:
  mysql: